//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Mehovoi_Eskiz.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class accessory
    {
        public double cost_per_pc { get; set; }
        public int pieces { get; set; }
        public int Mat_ID { get; set; }
    
        public virtual Material Material { get; set; }
    }
}
