//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Mehovoi_Eskiz.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_product
    {
        public string Prod_NAME { get; set; }
        public string Prod_Description { get; set; }
        public int Prod_ID { get; set; }
        public string Prod_Articul { get; set; }
        public int RU_size { get; set; }
    
        public virtual Default_Size Default_Size { get; set; }
        public virtual Catalog Catalog { get; set; }
        public virtual Product Product { get; set; }
    }
}
