//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Mehovoi_Eskiz.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalog
    {
        public string Prod_Name { get; set; }
        public string PhotoHyperlink { get; set; }
        public int Prod_ID { get; set; }
    
        public virtual Cat_product Cat_product { get; set; }
    }
}
