//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Mehovoi_Eskiz.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Custom
    {
        public Nullable<double> Breast { get; set; }
        public Nullable<double> Waste { get; set; }
        public Nullable<double> Back_width { get; set; }
        public Nullable<double> Hips { get; set; }
        public Nullable<double> shelf_height { get; set; }
        public Nullable<double> arm_length { get; set; }
        public Nullable<double> Chest_height { get; set; }
        public Nullable<double> shelf_width { get; set; }
        public Nullable<double> sleeve_length { get; set; }
        public Nullable<double> product_length { get; set; }
        public int Prod_ID { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
