//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Mehovoi_Eskiz.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public string AdminName { get; set; }
        public System.DateTime MsgDateTime { get; set; }
        public string MsgText { get; set; }
        public int User_ID { get; set; }
    
        public virtual Polzovatel Polzovatel { get; set; }
    }
}
