//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Mehovoi_Eskiz.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payed_Orders
    {
        public System.DateTime Payment_date { get; set; }
        public double Payment_sum { get; set; }
        public int Order_Number { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
